version: '3'

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /home/ilandols/data/wordpress_data

  mariadb_data:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /home/ilandols/data/mariadb_data

services:
  mariadb:
    image: mariadb:v42.0
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: ./.env
    expose:
      - "3306"
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress:v42.0
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: ./.env
    expose:
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: always

  nginx:
    image: nginx:v42.0
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    env_file: ./.env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: always