version: '3'

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - ./.env
    restart: always
    expose:
      - "3306"

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    expose:
      - "9000"
      - "3306"
    env_file:
      - ./.env
    restart: always
    expose:
      - "9000"
    
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
    env_file:
      - ./.env
    restart: always