version: '3'

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    env_file:
      - ./.env
    restart: unless-stopped

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    expose:
      - "9000"
    env_file:
      - ./.env
    restart: on-failure
    
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
    env_file:
      - ./.env
    restart: always



  # nginx:
  #   build: ./requirements/nginx 

  # wordpress:
  #   build: ./requirements/wordpress 

# services:
#   mariadb:
#     container_name: mariadb
#     networks:
#     - inception
#     build: 
#     context: requirements/mariadb
#     dockerfile: Dockerfile
#     env_file: .env
#     volumes:
#     - mariadb:/var/lib/mysql
#     restart: unless-stopped 
#     expose:
#     - "3306"

#   nginx:
#     container_name: nginx
#     volumes:
#     - wordpress:/var/www/wordpress
#     networks:
#     - inception
#     depends_on:
#     - wordpress
#     build: 
#     context: requirements/nginx
#     dockerfile: Dockerfile
#     env_file: .env
#     ports:
#     - "443:443"
#     restart: on-failure

#   wordpress:
#     container_name: wordpress
#     env_file: .env
#     volumes:
#     - wordpress:/var/www/wordpress
#     networks:
#     - inception
#     build: 
#     context: requirements/wordpress
#     dockerfile: Dockerfile
#     depends_on:
#     - mariadb
#     restart: on-failure
#     expose: 
#     - "9000"